version: 2

project_name: MediaWarp

snapshot:
  version_template: "{{ incpatch .Version }}-PreRelease-{{ .ShortCommit }}"

release:
  name_template: "{{ .Tag }}"
  extra_files:
    - glob: ./config/config.yaml.example
      name_template: config.yaml
    - glob: ./LICENSE

before:
  hooks:
    - go mod download

builds:
  - env:
      - GOPROXY=https://goproxy.io,direct
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "5"
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarm: 5
      - goos: windows
        goarm: 6
      - goos: windows
        goarm: 7
    binary: "{{ .ProjectName }}"
    ldflags:
      - -s -w
      - -X MediaWarp/internal/config.appVersion={{ .Version }}
      - -X MediaWarp/internal/config.commitHash={{ .FullCommit }}
      - -X MediaWarp/internal/config.buildDate={{ .Date }}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{- .Os }}_{{ .Arch }}{{- if .Arm}}v{{ .Arm }}{{- end}}"
    # 对于 Windows 存档使用 zip 格式
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src: LICENSE
      - src: README.md
      - src: config/config.yaml.example
        dst: config.yaml.example

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"
      - "^release:"
      - "^issue:"
      - "^MediaWarp"
